---
- name: Install packages
  hosts: all
  gather_facts: false
  tasks:
    - name: Install httpd and firewalld
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
