---
- name: Test Playbook
  hosts: all
  gather_facts: false
  tasks: 
  - name: Printing a Message
    debug: 
      msg: "Hello World\n"
      
  - name: Create files
    file:
      path: /root/ansible
      state: touch
      
     
